// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 20/06/2026, 15:21:16
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/marzeero/Documentos/seConecta-site/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/marzeero/Documentos/seConecta-site/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/marzeero/Documentos/seConecta-site/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/marzeero/Documentos/seConecta-site/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/marzeero/Documentos/seConecta-site/plugins/**/*.{js,ts,mjs}","/home/marzeero/Documentos/seConecta-site/composables/**/*.{js,ts,mjs}","/home/marzeero/Documentos/seConecta-site/utils/**/*.{js,ts,mjs}","/home/marzeero/Documentos/seConecta-site/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/marzeero/Documentos/seConecta-site/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/marzeero/Documentos/seConecta-site/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/marzeero/Documentos/seConecta-site/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;