<<<<<<< HEAD
// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 30/03/2026, 06:08:32
=======
// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 28/03/2026, 15:46:16
>>>>>>> 4c29043d9c5f2df4226927e6c7f5793f6208daa5
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/mastersons/Documentos/CRISTOREY/SeConectaThings/seConecta-site/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/mastersons/Documentos/CRISTOREY/SeConectaThings/seConecta-site/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/mastersons/Documentos/CRISTOREY/SeConectaThings/seConecta-site/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/mastersons/Documentos/CRISTOREY/SeConectaThings/seConecta-site/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/mastersons/Documentos/CRISTOREY/SeConectaThings/seConecta-site/plugins/**/*.{js,ts,mjs}","/home/mastersons/Documentos/CRISTOREY/SeConectaThings/seConecta-site/composables/**/*.{js,ts,mjs}","/home/mastersons/Documentos/CRISTOREY/SeConectaThings/seConecta-site/utils/**/*.{js,ts,mjs}","/home/mastersons/Documentos/CRISTOREY/SeConectaThings/seConecta-site/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/mastersons/Documentos/CRISTOREY/SeConectaThings/seConecta-site/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/mastersons/Documentos/CRISTOREY/SeConectaThings/seConecta-site/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/mastersons/Documentos/CRISTOREY/SeConectaThings/seConecta-site/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;